Traceback (most recent call last):
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\core\__init__.py", line 24, in <module>  
    from . import multiarray
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\core\overrides.py", line 8, in <module>  
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\python.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\S-FAMILY\Desktop\run\SAZOM.py", line 6, in <module>
    from rembg import remove
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\rembg\bg.py", line 5, in <module>
    import numpy as np
  File "C:\Users\S-FAMILY\AppData\Local\Programs\Python\Python39-32\lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
